Develop
Vladimir-Leushkin/java-filmorate pull request #16
Opened 2022-08-25 06:03 UTC by IgorMartynkin1981

2022-08-25 07:09 UTC, kukolev requested changes

2022-08-25 07:09 UTC, kukolev commented on src/main/java/ru/yandex/practicum/javafilmorate/service/ReviewService.java
> +        eventService.addEvent(findReviewById(review.getReviewId()).getUserId(), review.getReviewId(), EventType.REVIEW, OperationType.UPDATE);
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-08-25 07:09 UTC, kukolev commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS REVIEWS
Здесь и ниже запросы написаны в верхнем регистре, а до этого в нижнем. Нужно привести к одному стилю для единообразия. Так код будет восприниматься лучше.

2022-08-25 07:25 UTC, IgorMartynkin1981 commented on src/main/java/ru/yandex/practicum/javafilmorate/controller/ReviewController.java
> +ReviewController {
+

2022-08-25 07:25 UTC, IgorMartynkin1981 commented on src/main/java/ru/yandex/practicum/javafilmorate/dao/ReviewDbStorage.java
> +        String sql = "SELECT r.ID_REVIEW AS id_review, r.CONTENT AS content, r.is_positive AS is_positive, r.user_id AS user_id, r.film_id AS film_id, SUM(rr.RATE) AS useful\n" +
+

2022-08-25 07:25 UTC, IgorMartynkin1981 commented on src/main/java/ru/yandex/practicum/javafilmorate/dao/ReviewDbStorage.java
> +        String sql = "SELECT r.ID_REVIEW AS id_review, r.CONTENT AS content, r.is_positive AS is_positive, r.user_id AS user_id, r.film_id AS film_id, SUM(rr.RATE) AS useful\n" +
+

2022-08-25 07:25 UTC, IgorMartynkin1981 commented on src/main/java/ru/yandex/practicum/javafilmorate/dao/ReviewDbStorage.java
> +        String sql = "SELECT r.ID_REVIEW AS id_review, r.CONTENT AS content, r.is_positive AS is_positive, r.user_id AS user_id, r.film_id AS film_id, SUM(rr.RATE) AS useful\n" +
+

2022-08-25 07:26 UTC, IgorMartynkin1981 commented on src/main/java/ru/yandex/practicum/javafilmorate/service/ReviewService.java
> +        eventService.addEvent(findReviewById(review.getReviewId()).getUserId(), review.getReviewId(), EventType.REVIEW, OperationType.UPDATE);
+

2022-08-25 07:44 UTC, IgorMartynkin1981 commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS REVIEWS
+

2022-08-25 16:28 UTC, kukolev requested changes

2022-08-25 16:28 UTC, kukolev commented on src/main/java/ru/yandex/practicum/javafilmorate/service/FilmService.java
> +        if (checkFilmById(id)) {
Эту проверку можно убрать, т.к. метод checkFilmById всегда возвращает true. Если фильм не прошел проверку, то будет выброшено исключение.

2022-08-25 16:28 UTC, kukolev commented on src/main/java/ru/yandex/practicum/javafilmorate/dao/DirectorDbStorage.java
> +                rs.getString("DIRECTOR_NAME")
По моему этот перенос на новую строку лишний. Код будет читаться лучше без переноса.

2022-08-25 16:28 UTC, kukolev commented on src/main/java/ru/yandex/practicum/javafilmorate/service/ReviewService.java
> +            throw new NotFoundException("test");
По моему тут некорректное сообщение. Нужно поправить. или удалить.

2022-08-25 21:31 UTC, IgorMartynkin1981 commented on src/main/java/ru/yandex/practicum/javafilmorate/service/FilmService.java
> +        if (checkFilmById(id)) {
Проверку убрал

2022-08-25 21:32 UTC, IgorMartynkin1981 commented on src/main/java/ru/yandex/practicum/javafilmorate/dao/DirectorDbStorage.java
> +                rs.getString("DIRECTOR_NAME")
Согласен, перенос убрал.

2022-08-25 21:36 UTC, IgorMartynkin1981 commented on src/main/java/ru/yandex/practicum/javafilmorate/service/ReviewService.java
> +            throw new NotFoundException("test");
Заменил некорректное сообщение

2022-08-26 15:26 UTC, kukolev commented on src/main/java/ru/yandex/practicum/javafilmorate/service/FilmService.java
> +        if (checkFilmById(id)) {
Это хорошо, но можно еще лучше - написал в общем комменте.

2022-08-26 17:31 UTC, IgorMartynkin1981 commented
Замечания исправлены, методы сделаны void

2022-08-26 21:05 UTC, kukolev approved these changes

2022-08-27 08:28 UTC, merged